storage:
  dbPath: "/data/mongodb"
  directoryPerDB: true
  journal:
    enabled: true
systemLog:
  destination: file
  path: "/data/mongodb/mongodb.log"
  logAppend: true
  timeStampFormat: iso8601-utc
processManagement:
  fork: true
net:
  bindIp: 127.0.0.1
  port: 27017
  wireObjectCheck : false
  unixDomainSocket: 
    enabled : true